### PR TITLE
[WIP] Remove the $CARGO_HOME environment variable if it exists, as we do not use it …

### LINKED ISSUE #193: Errors when setting CARGO_HOME
Setting the `CARGO_HOME` environment variable causes the following errors to appear: `Update for <crate> could not be found!` Setting `CARGO_HOME` to a different path doesn't seem to change the behavior.

## Steps to reproduce
```bash
$ cargo new issue
     Created binary (application) `issue` package
$ cd issue/
$ vim Cargo.toml # log = "=0.4.0"
$ cargo outdated
Name  Project  Compat  Latest  Kind    Platform
----  -------  ------  ------  ----    --------
log   0.4.0    ---     0.4.8   Normal  ---
$ export CARGO_HOME=cargo
$ cargo outdated
Update for serde could not be found!
Update for serde_test could not be found!
Update for compiler_builtins could not be found!
Name  Project  Compat  Latest  Kind    Platform
----  -------  ------  ------  ----    --------
log   0.4.0    ---     0.4.8   Normal  ---
$ unset CARGO_HOME
$ cd ..
$ cargo new issue2
     Created binary (application) `issue2` package
$ cd issue2/
$ vim Cargo.toml # regex = "=1.2.0"
$ cargo outdated
Name                 Project  Compat  Latest   Kind    Platform
----                 -------  ------  ------   ----    --------
regex                1.2.0    ---     1.3.3    Normal  ---
regex->thread_local  0.3.6    ---     1.0.1    Normal  ---
regex->utf8-ranges   1.0.4    ---     Removed  Normal  ---
$ export CARGO_HOME=cargo
$ cargo outdated
Update for doc-comment could not be found!
Update for doc-comment could not be found!
Update for doc-comment could not be found!
Update for libc could not be found!
Update for quickcheck could not be found!
Update for spin could not be found!
Update for doc-comment could not be found!
Name                 Project  Compat  Latest   Kind    Platform
----                 -------  ------  ------   ----    --------
regex                1.2.0    ---     1.3.3    Normal  ---
regex->thread_local  0.3.6    ---     1.0.1    Normal  ---
regex->utf8-ranges   1.0.4    ---     Removed  Normal  ---

### PR DESCRIPTION
**Pull request by deg4uss3r**
…for dependency resolution and it will point cargo to the wrong location to check the dependency cache

Resolves #193  

No sure it's the most elegant solution, thoughts?

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -103,6 +103,15 @@ fn main() {
         options
     };
 
+    // Check if $CARGO_HOME is set before capturing the config environment 
+    // if it is, remove it, we build the project in a temporary directory
+    match std::env::var("CARGO_HOME") {
```
Comment (lzutao) [inline src/main.rs]:
```suggestion
    if std::env::var_os("CARGO_HOME").is_some() {
```

File: src/main.rs [hunk 2]
```diff
@@ -105,7 +105,7 @@ fn main() {
 
     // Check if $CARGO_HOME is set before capturing the config environment 
     // if it is, remove it, we build the project in a temporary directory
-    match std::env::var("CARGO_HOME") {
+    if std::env::var_os("CARGO_HOME").is_some() {
         Ok(_) => {
```
Comment (lzutao) [inline src/main.rs]:
```suggestion
```

Comment (deg4uss3r) [reply src/main.rs]: Fixed manually, github messed up the line wrapping I think?
